version: '3'

services:
        # uwsgi:
        #         build: .
        #         command: ./config/uwsgi.sh
        #         volumes:
        #                 - /static
        #         links:
        #                 - web
        #Ark's homepage container
        web:
                build: .
                command: python manage.py runserver 0.0.0.0:8000
                volumes:
                        - .:/web
                environment:
                        VIRTUAL_HOST: loalhost
                # expose:
                #         - "8000:80"
                links:
                        - db
                depends_on:
                        - db
        db:
                image: postgres:10
                environment:
                        POSTGRES_DB: "database"
                        POSTGRES_USER: "postgres"loalhostloalhost
                        POSTGRES_PASSWORD: "postgres"
                ports:
                        - 5432:5432
                volumes:
                        - ~/docker/postgres:/var/lib/postgresql/homepagedata

networks:
  default:
    external:
      name: common_link