version: '3'

networks:
  default:
    external:
      name: common_link
volumes:
  ark-volume:
    driver: 'local'
services:
        web:
                build: .
                command: python manage.py runserver 0.0.0.0:8000
                volumes:
                        - .:/web
                environment:
                        VIRTUAL_HOST: home.loalhost
                links:
                        - db
                depends_on:
                        - db
        db:
                image: postgres:10
                environment:
                        POSTGRES_DB: "database"
                        POSTGRES_USER: "postgres"
                        POSTGRES_PASSWORD: "postgres"
                ports:
                        - 5432:5432
                volumes:
                        - ~/docker/postgres:/var/lib/postgresql/homepagedata
        # uwsgi:
        #         build: .
        #         command: ./config/uwsgi.sh
        #         volumes:
        #                 - /static
        #         links:
        #                 - web
        #Ark's homepage container
