version: '3'

services:
        # uwsgi:
        #         build: .
        #         command: ./config/uwsgi.sh
        #         volumes:
        #                 - /static
        #         links:
        #                 - web
        web:
        #Ark's homepage container
                build: .
                command: python manage.py runserver 0.0.0.0:8000
                volumes:
                        - .:/web
                environment:
                VIRTUAL_HOST: home.ark-cg.com
                expose:
                        - "8000"
                depends_on:
                        - db
        db:
                image: postgres:10
                environment:
                        POSTGRES_DB: "database"
                        POSTGRES_USER: "postgres"
                        POSTGRES_PASSWORD: "postgres"
                ports:
                        - 5432:5432
                volumes:
                        - ~/docker/postgres:/var/lib/postgresql/data
